plugins {
    id 'net.fabricmc.fabric-loom' version "1.16-SNAPSHOT"
    id 'maven-publish'
}

base {
    archivesName = project.archives_base_name
}
version = project.mod_version
group = project.maven_group

repositories {
    maven { url = "https://maven.shedaniel.me" }
    // for FTL
    maven {
        name = "Technici4n"
        url = "https://raw.githubusercontent.com/Technici4n/Technici4n-maven/master/"
        content {
            includeGroup "net.fabricmc.fabric-api" // until fabric-api-lookup-api-v1 is merged
            includeGroup "dev.technici4n"
        }
    }
    maven { url = "https://maven.terraformersmc.com/releases/" }
    maven { url = "https://maven.fzzyhmstrs.me/" }
    maven { url = "https://maven.ladysnake.org/releases" }
    mavenLocal()
}

dependencies {
    minecraft("com.mojang:minecraft:${project.minecraft_version}")
    implementation("net.fabricmc:fabric-loader:${project.loader_version}")
    implementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_version}")
    
    implementation("me.fzzyhmstrs:fzzy_config:${project.fzzy_config_version}")
    
    //implementation("me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}") {
    //    exclude(group: "net.fabricmc.fabric-api")
    //    exclude(group: "io.github.prospector")
    //}
    //implementation "dev.architectury:architectury-fabric:6.3.49"
    implementation(include("teamreborn:energy:${project.tr_energy_version}"))
    //implementation(include("net.devtech:arrp:${project.arrp_version}"))
    
    compileOnly "eu.pb4:trinkets:4.0.0-beta.1+26.1"
}

processResources {
    def modVersion = project.version
    inputs.property "version", modVersion

    filesMatching("fabric.mod.json") {
        expand "version": modVersion
    }
}

// ensure that the encoding is set to UTF-8, no matter what the system default is
// this fixes some edge cases with special characters not displaying correctly
// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
    options.release = 25
    options.compilerArgs << "-Xlint:deprecation"
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from "LICENSE"
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    // select the repositories you want to publish to
    repositories {
        // uncomment to publish to the local maven
        // mavenLocal()
    }
}