import re
import glob

def revert_html(match):
    img_src = match.group(1)
    alt_text = match.group(2)
    # The current paths might be ../../image/generated/..., but we want ../image/generated/... 
    # if it's recipes/ or jetpacks/ which use depth 1. 
    # Wait, recipes/coils.md is depth 1, so it should be ../image
    # Let's clean the path. If it starts with ../../, change to ../
    img_src = img_src.replace("../../image", "../image")
    return f"![{alt_text}]({img_src})"

for md_file in glob.glob("jetpacks/*.md") + glob.glob("recipes/*.md") + glob.glob("upgrades/*.md"):
    with open(md_file, "r") as f:
        content = f.read()
        
    # Revert HTML blocks generated by our previous script
    # Pattern looks for <div class="crafting-container"... <img src="X" alt="Y"... </div>
    # Needs to match robustly across lines
    content = re.sub(r'<div class="crafting-container"[^>]*>\s*<img src="([^"]+)" alt="([^"]+)"[^>]*>.*?</div>', revert_html, content, flags=re.DOTALL)
    
    with open(md_file, "w") as f:
        f.write(content)
